FROM grafana/grafana-oss:12.3.3

COPY apps/observability/grafana/provisioning/datasources /etc/grafana/provisioning/datasources
COPY apps/observability/grafana/provisioning/dashboards /etc/grafana/provisioning/dashboards

EXPOSE 3000

CMD [""]
