services:
  nginx:
    build:
      context: .
      dockerfile: apps/nginx/Dockerfile
    image: europe-north1-docker.pkg.dev/chat-application-13/nginx/server:0.1.0

  auth:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
    image: europe-north1-docker.pkg.dev/chat-application-13/auth/api:0.1.0

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    image: europe-north1-docker.pkg.dev/chat-application-13/backend/api:0.1.0

  socket:
    build:
      context: .
      dockerfile: apps/socket-go/Dockerfile
    image: europe-north1-docker.pkg.dev/chat-application-13/socket-go/ws:0.1.0

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile.prod
    image: europe-north1-docker.pkg.dev/chat-application-13/frontend/app:0.1.0

  chat-worker:
    build:
      context: .
      dockerfile: apps/chat-worker/Dockerfile
    image: europe-north1-docker.pkg.dev/chat-application-13/chat-worker/app:0.1.0

  loki:
    build:
      context: .
      dockerfile: apps/loki/Dockerfile
    image: europe-north1-docker.pkg.dev/chat-application-13/loki/server:0.1.0

  alloy:
    build:
      context: .
      dockerfile: apps/alloy/Dockerfile
    image: europe-north1-docker.pkg.dev/chat-application-13/alloy/server:0.1.0

  grafana:
    build:
      context: .
      dockerfile: apps/grafana/Dockerfile
    image: europe-north1-docker.pkg.dev/chat-application-13/grafana/server:0.1.0

  fluent-bit:
    build:
      context: .
      dockerfile: apps/fluent-bit/Dockerfile
    image: europe-north1-docker.pkg.dev/chat-application-13/fluent-bit/server:0.1.0
