packages:
  - apps/frontend
  - scripts/seed
  - tests/e2e
  - tests/load
  - tests/resilience

onlyBuiltDependencies:
  - '@arpansaha13/utils'
  - '@parcel/watcher'
  - cpu-features
  - esbuild
  - protobufjs
  - sharp
  - ssh2
  - unrs-resolver
  - vue-demi
