// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/user_profile.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserProfileData contains profile information for a user.
type UserProfileData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`            // Bigint ID matching users.id
	GlobalName    string                 `protobuf:"bytes,2,opt,name=global_name,json=globalName,proto3" json:"global_name,omitempty"` // Display name (separate from auth users.name)
	Dp            string                 `protobuf:"bytes,3,opt,name=dp,proto3" json:"dp,omitempty"`                                   // Avatar URL (empty string means no avatar set)
	Bio           string                 `protobuf:"bytes,4,opt,name=bio,proto3" json:"bio,omitempty"`                                 // Short biography text
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfileData) Reset() {
	*x = UserProfileData{}
	mi := &file_proto_user_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfileData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfileData) ProtoMessage() {}

func (x *UserProfileData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfileData.ProtoReflect.Descriptor instead.
func (*UserProfileData) Descriptor() ([]byte, []int) {
	return file_proto_user_profile_proto_rawDescGZIP(), []int{0}
}

func (x *UserProfileData) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserProfileData) GetGlobalName() string {
	if x != nil {
		return x.GlobalName
	}
	return ""
}

func (x *UserProfileData) GetDp() string {
	if x != nil {
		return x.Dp
	}
	return ""
}

func (x *UserProfileData) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UserProfileData) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserProfileData) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CreateUserProfileRequest creates a profile for a newly registered user.
type CreateUserProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`            // Must match an existing users.id
	GlobalName    string                 `protobuf:"bytes,2,opt,name=global_name,json=globalName,proto3" json:"global_name,omitempty"` // Initial display name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserProfileRequest) Reset() {
	*x = CreateUserProfileRequest{}
	mi := &file_proto_user_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserProfileRequest) ProtoMessage() {}

func (x *CreateUserProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserProfileRequest.ProtoReflect.Descriptor instead.
func (*CreateUserProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_profile_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserProfileRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateUserProfileRequest) GetGlobalName() string {
	if x != nil {
		return x.GlobalName
	}
	return ""
}

// CreateUserProfileResponse returns the newly created profile.
type CreateUserProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *UserProfileData       `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserProfileResponse) Reset() {
	*x = CreateUserProfileResponse{}
	mi := &file_proto_user_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserProfileResponse) ProtoMessage() {}

func (x *CreateUserProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserProfileResponse.ProtoReflect.Descriptor instead.
func (*CreateUserProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_profile_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUserProfileResponse) GetProfile() *UserProfileData {
	if x != nil {
		return x.Profile
	}
	return nil
}

// GetUserProfileRequest fetches a single profile by user ID.
type GetUserProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfileRequest) Reset() {
	*x = GetUserProfileRequest{}
	mi := &file_proto_user_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileRequest) ProtoMessage() {}

func (x *GetUserProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileRequest.ProtoReflect.Descriptor instead.
func (*GetUserProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_profile_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserProfileRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// GetUserProfileResponse returns the profile.
type GetUserProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *UserProfileData       `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfileResponse) Reset() {
	*x = GetUserProfileResponse{}
	mi := &file_proto_user_profile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileResponse) ProtoMessage() {}

func (x *GetUserProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_profile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileResponse.ProtoReflect.Descriptor instead.
func (*GetUserProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_profile_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserProfileResponse) GetProfile() *UserProfileData {
	if x != nil {
		return x.Profile
	}
	return nil
}

// GetUserProfilesRequest fetches multiple profiles by user IDs (batch).
type GetUserProfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []int64                `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfilesRequest) Reset() {
	*x = GetUserProfilesRequest{}
	mi := &file_proto_user_profile_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfilesRequest) ProtoMessage() {}

func (x *GetUserProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_profile_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfilesRequest.ProtoReflect.Descriptor instead.
func (*GetUserProfilesRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_profile_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserProfilesRequest) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

// GetUserProfilesResponse returns a map of user_id -> profile.
type GetUserProfilesResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Profiles      map[int64]*UserProfileData `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfilesResponse) Reset() {
	*x = GetUserProfilesResponse{}
	mi := &file_proto_user_profile_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfilesResponse) ProtoMessage() {}

func (x *GetUserProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_profile_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfilesResponse.ProtoReflect.Descriptor instead.
func (*GetUserProfilesResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_profile_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserProfilesResponse) GetProfiles() map[int64]*UserProfileData {
	if x != nil {
		return x.Profiles
	}
	return nil
}

// UpdateUserProfileRequest updates mutable profile fields.
// Fields left empty will not be modified.
type UpdateUserProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GlobalName    string                 `protobuf:"bytes,2,opt,name=global_name,json=globalName,proto3" json:"global_name,omitempty"`
	Dp            string                 `protobuf:"bytes,3,opt,name=dp,proto3" json:"dp,omitempty"`
	Bio           string                 `protobuf:"bytes,4,opt,name=bio,proto3" json:"bio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserProfileRequest) Reset() {
	*x = UpdateUserProfileRequest{}
	mi := &file_proto_user_profile_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserProfileRequest) ProtoMessage() {}

func (x *UpdateUserProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_profile_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_profile_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateUserProfileRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUserProfileRequest) GetGlobalName() string {
	if x != nil {
		return x.GlobalName
	}
	return ""
}

func (x *UpdateUserProfileRequest) GetDp() string {
	if x != nil {
		return x.Dp
	}
	return ""
}

func (x *UpdateUserProfileRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

// UpdateUserProfileResponse returns the updated profile.
type UpdateUserProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *UserProfileData       `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserProfileResponse) Reset() {
	*x = UpdateUserProfileResponse{}
	mi := &file_proto_user_profile_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserProfileResponse) ProtoMessage() {}

func (x *UpdateUserProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_profile_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_profile_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateUserProfileResponse) GetProfile() *UserProfileData {
	if x != nil {
		return x.Profile
	}
	return nil
}

// SearchUserProfilesRequest searches profiles by global_name.
type SearchUserProfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // Max results to return (default 20)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUserProfilesRequest) Reset() {
	*x = SearchUserProfilesRequest{}
	mi := &file_proto_user_profile_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUserProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUserProfilesRequest) ProtoMessage() {}

func (x *SearchUserProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_profile_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUserProfilesRequest.ProtoReflect.Descriptor instead.
func (*SearchUserProfilesRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_profile_proto_rawDescGZIP(), []int{9}
}

func (x *SearchUserProfilesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchUserProfilesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// SearchUserProfilesResponse returns matching profiles.
type SearchUserProfilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      []*UserProfileData     `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUserProfilesResponse) Reset() {
	*x = SearchUserProfilesResponse{}
	mi := &file_proto_user_profile_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUserProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUserProfilesResponse) ProtoMessage() {}

func (x *SearchUserProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_profile_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUserProfilesResponse.ProtoReflect.Descriptor instead.
func (*SearchUserProfilesResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_profile_proto_rawDescGZIP(), []int{10}
}

func (x *SearchUserProfilesResponse) GetProfiles() []*UserProfileData {
	if x != nil {
		return x.Profiles
	}
	return nil
}

var File_proto_user_profile_proto protoreflect.FileDescriptor

const file_proto_user_profile_proto_rawDesc = "" +
	"\n" +
	"\x18proto/user_profile.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe3\x01\n" +
	"\x0fUserProfileData\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vglobal_name\x18\x02 \x01(\tR\n" +
	"globalName\x12\x0e\n" +
	"\x02dp\x18\x03 \x01(\tR\x02dp\x12\x10\n" +
	"\x03bio\x18\x04 \x01(\tR\x03bio\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"T\n" +
	"\x18CreateUserProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vglobal_name\x18\x02 \x01(\tR\n" +
	"globalName\"M\n" +
	"\x19CreateUserProfileResponse\x120\n" +
	"\aprofile\x18\x01 \x01(\v2\x16.proto.UserProfileDataR\aprofile\"0\n" +
	"\x15GetUserProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"J\n" +
	"\x16GetUserProfileResponse\x120\n" +
	"\aprofile\x18\x01 \x01(\v2\x16.proto.UserProfileDataR\aprofile\"3\n" +
	"\x16GetUserProfilesRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\x03R\auserIds\"\xb8\x01\n" +
	"\x17GetUserProfilesResponse\x12H\n" +
	"\bprofiles\x18\x01 \x03(\v2,.proto.GetUserProfilesResponse.ProfilesEntryR\bprofiles\x1aS\n" +
	"\rProfilesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.proto.UserProfileDataR\x05value:\x028\x01\"v\n" +
	"\x18UpdateUserProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vglobal_name\x18\x02 \x01(\tR\n" +
	"globalName\x12\x0e\n" +
	"\x02dp\x18\x03 \x01(\tR\x02dp\x12\x10\n" +
	"\x03bio\x18\x04 \x01(\tR\x03bio\"M\n" +
	"\x19UpdateUserProfileResponse\x120\n" +
	"\aprofile\x18\x01 \x01(\v2\x16.proto.UserProfileDataR\aprofile\"G\n" +
	"\x19SearchUserProfilesRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"P\n" +
	"\x1aSearchUserProfilesResponse\x122\n" +
	"\bprofiles\x18\x01 \x03(\v2\x16.proto.UserProfileDataR\bprofiles2\xc0\x03\n" +
	"\x12UserProfileService\x12V\n" +
	"\x11CreateUserProfile\x12\x1f.proto.CreateUserProfileRequest\x1a .proto.CreateUserProfileResponse\x12M\n" +
	"\x0eGetUserProfile\x12\x1c.proto.GetUserProfileRequest\x1a\x1d.proto.GetUserProfileResponse\x12P\n" +
	"\x0fGetUserProfiles\x12\x1d.proto.GetUserProfilesRequest\x1a\x1e.proto.GetUserProfilesResponse\x12V\n" +
	"\x11UpdateUserProfile\x12\x1f.proto.UpdateUserProfileRequest\x1a .proto.UpdateUserProfileResponse\x12Y\n" +
	"\x12SearchUserProfiles\x12 .proto.SearchUserProfilesRequest\x1a!.proto.SearchUserProfilesResponseB8Z6github.com/arpansaha13/messaging-system/apps/common/pbb\x06proto3"

var (
	file_proto_user_profile_proto_rawDescOnce sync.Once
	file_proto_user_profile_proto_rawDescData []byte
)

func file_proto_user_profile_proto_rawDescGZIP() []byte {
	file_proto_user_profile_proto_rawDescOnce.Do(func() {
		file_proto_user_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_profile_proto_rawDesc), len(file_proto_user_profile_proto_rawDesc)))
	})
	return file_proto_user_profile_proto_rawDescData
}

var file_proto_user_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_user_profile_proto_goTypes = []any{
	(*UserProfileData)(nil),            // 0: proto.UserProfileData
	(*CreateUserProfileRequest)(nil),   // 1: proto.CreateUserProfileRequest
	(*CreateUserProfileResponse)(nil),  // 2: proto.CreateUserProfileResponse
	(*GetUserProfileRequest)(nil),      // 3: proto.GetUserProfileRequest
	(*GetUserProfileResponse)(nil),     // 4: proto.GetUserProfileResponse
	(*GetUserProfilesRequest)(nil),     // 5: proto.GetUserProfilesRequest
	(*GetUserProfilesResponse)(nil),    // 6: proto.GetUserProfilesResponse
	(*UpdateUserProfileRequest)(nil),   // 7: proto.UpdateUserProfileRequest
	(*UpdateUserProfileResponse)(nil),  // 8: proto.UpdateUserProfileResponse
	(*SearchUserProfilesRequest)(nil),  // 9: proto.SearchUserProfilesRequest
	(*SearchUserProfilesResponse)(nil), // 10: proto.SearchUserProfilesResponse
	nil,                                // 11: proto.GetUserProfilesResponse.ProfilesEntry
	(*timestamppb.Timestamp)(nil),      // 12: google.protobuf.Timestamp
}
var file_proto_user_profile_proto_depIdxs = []int32{
	12, // 0: proto.UserProfileData.created_at:type_name -> google.protobuf.Timestamp
	12, // 1: proto.UserProfileData.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: proto.CreateUserProfileResponse.profile:type_name -> proto.UserProfileData
	0,  // 3: proto.GetUserProfileResponse.profile:type_name -> proto.UserProfileData
	11, // 4: proto.GetUserProfilesResponse.profiles:type_name -> proto.GetUserProfilesResponse.ProfilesEntry
	0,  // 5: proto.UpdateUserProfileResponse.profile:type_name -> proto.UserProfileData
	0,  // 6: proto.SearchUserProfilesResponse.profiles:type_name -> proto.UserProfileData
	0,  // 7: proto.GetUserProfilesResponse.ProfilesEntry.value:type_name -> proto.UserProfileData
	1,  // 8: proto.UserProfileService.CreateUserProfile:input_type -> proto.CreateUserProfileRequest
	3,  // 9: proto.UserProfileService.GetUserProfile:input_type -> proto.GetUserProfileRequest
	5,  // 10: proto.UserProfileService.GetUserProfiles:input_type -> proto.GetUserProfilesRequest
	7,  // 11: proto.UserProfileService.UpdateUserProfile:input_type -> proto.UpdateUserProfileRequest
	9,  // 12: proto.UserProfileService.SearchUserProfiles:input_type -> proto.SearchUserProfilesRequest
	2,  // 13: proto.UserProfileService.CreateUserProfile:output_type -> proto.CreateUserProfileResponse
	4,  // 14: proto.UserProfileService.GetUserProfile:output_type -> proto.GetUserProfileResponse
	6,  // 15: proto.UserProfileService.GetUserProfiles:output_type -> proto.GetUserProfilesResponse
	8,  // 16: proto.UserProfileService.UpdateUserProfile:output_type -> proto.UpdateUserProfileResponse
	10, // 17: proto.UserProfileService.SearchUserProfiles:output_type -> proto.SearchUserProfilesResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_user_profile_proto_init() }
func file_proto_user_profile_proto_init() {
	if File_proto_user_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_profile_proto_rawDesc), len(file_proto_user_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_user_profile_proto_goTypes,
		DependencyIndexes: file_proto_user_profile_proto_depIdxs,
		MessageInfos:      file_proto_user_profile_proto_msgTypes,
	}.Build()
	File_proto_user_profile_proto = out.File
	file_proto_user_profile_proto_goTypes = nil
	file_proto_user_profile_proto_depIdxs = nil
}
