import Head from 'next/head'

import type { ReactNode } from 'react'

interface DefaultLayoutProps {
  children: ReactNode
}

export default function DefaultLayout({ children }: DefaultLayoutProps) {
  return (
    <div className='px-5 py-4 w-screen h-screen'>
      <Head>
        <title>WhatsApp Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      { children }
    </div>
  )
}
