import Head from 'next/head'
import Router from 'next/router'
import NextLink from 'next/link'
import shallow from 'zustand/shallow'

import { useEffect } from 'react'
import { useMap } from 'react-use'
// Custom Hooks
import { useFetch } from '../../hooks/useFetch'
// Components
import BaseInput from '../../components/base/BaseInput'
// Stores
import { useStore } from '../../stores/index.store'
import { useAuthStore } from '../../stores/useAuthStore'
// Layout
import AuthLayout from '../../layouts/auth'
// Types
import type { FormEvent, ReactElement } from 'react'
import type { JwtToken } from '../../types/index.types'

const SignInPage = () => {
  const expiresAt = useAuthStore(state => state.authExpiresAt)

  useEffect(() => {
    if (expiresAt !== null && Date.now() < expiresAt) {
      Router.replace('/')
    }
    Router.prefetch('/')
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const fetchHook = useFetch()
  const setAuthState = useAuthStore(state => state.setAuthState)
  const [toggleNotification, setNotification] = useStore(
    state => [state.toggleNotification, state.setNotification],
    shallow,
  )

  const [formData, { set }] = useMap({
    email: '',
    password: '',
  })

  function signIn(e: FormEvent<HTMLFormElement>) {
    e.preventDefault()

    fetchHook('auth/sign-in', {
      method: 'POST',
      body: JSON.stringify(formData),
    })
      .then((data: JwtToken) => {
        setAuthState({
          authToken: data.authToken,
          authExpiresAt: data.expiresAt,
        })
        Router.replace('/')
        toggleNotification(false)
      })
      .catch(err => {
        setNotification({
          status: 'error',
          title: 'Sign in failed!',
          description: err.message,
        })
        toggleNotification(true)
      })
  }

  return (
    <>
      <Head>
        <title>WhatsApp Clone | Sign in</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <form className="space-y-6" onSubmit={signIn}>
        <BaseInput
          id="email"
          name="email"
          type="email"
          autoComplete="email"
          required
          label="Email address"
          value={formData.email}
          onChange={e => set('email', e.target.value)}
        />

        <BaseInput
          id="password"
          name="password"
          type="password"
          autoComplete="current-password"
          required
          label="Password"
          value={formData.password}
          onChange={e => set('password', e.target.value)}
        />

        <div className="flex items-center justify-end">
          <div className="text-sm">
            <a href="#" className="font-medium text-emerald-600 hover:text-emerald-500">
              Forgot your password?
            </a>
          </div>
        </div>

        <div>
          <button
            type="submit"
            className="flex w-full justify-center rounded-md border border-transparent bg-emerald-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-emerald-700 focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:ring-offset-2"
          >
            Sign in
          </button>
        </div>

        <div className="flex items-center justify-start">
          <div className="text-sm">
            <span className="text-gray-100">Don&apos;t have an account?</span>{' '}
            <NextLink href="/auth/signup">
              <span className="font-medium text-emerald-600 hover:text-emerald-500 cursor-pointer">Sign up</span>
            </NextLink>
          </div>
        </div>
      </form>
    </>
  )
}
SignInPage.getLayout = (page: ReactElement) => <AuthLayout heading="Sign in to your account">{page}</AuthLayout>
export default SignInPage
