# Parser for JSON logs from zap
[PARSER]
    Name        json_parser
    Format      json
    Time_Key    timestamp
    # This format handles the standard Zap ISO8601 output
    Time_Format %Y-%m-%dT%H:%M:%S.%L%z
    Time_Keep   On