{
 "title": "Backend Server Metrics (HTTP)",
 "description": "Dashboard for Golang builtin Host & Runtime metrics",
 "tags": [
  "go",
  "http",
  "server"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "job", "query": { "query": "label_values(up, job)" } }
  ]
 },
 "panels": [
  {
   "title": "cpu - system seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "system_cpu_time_seconds_total{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cpu - process seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "process_cpu_time_seconds_total{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mem - system utilization ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "system_memory_utilization_ratio{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mem - system usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "system_memory_usage_bytes{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mem - process idle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_runtime_go_mem_heap_idle_bytes{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mem - process alloc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_runtime_go_mem_heap_alloc_bytes{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mem - process inuse",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_runtime_go_mem_heap_inuse_bytes{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mem - process released",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_runtime_go_mem_heap_released_bytes{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mem - heap sys",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_runtime_go_mem_heap_sys_bytes{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mem - live objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "process_runtime_go_mem_live_objects{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mem - heap objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "process_runtime_go_mem_heap_objects{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mem - lookups total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "targets": [
    {
     "expr": "process_runtime_go_mem_lookups_total{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "network - io total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "system_network_io_bytes_total{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "uptime - total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "runtime_uptime_milliseconds_total{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cgo - calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "process_runtime_go_cgo_calls{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "routines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "targets": [
    {
     "expr": "process_runtime_go_goroutines{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gc - total count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "process_runtime_go_gc_count_total{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gc - pause ns bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 32 },
   "targets": [
    {
     "expr": "process_runtime_go_gc_pause_ns_bucket{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gc - pause ns sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "process_runtime_go_gc_pause_ns_sum{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gc - pause ns count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 32 },
   "targets": [
    {
     "expr": "process_runtime_go_gc_pause_ns_count{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gc - pause ns total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "process_runtime_go_gc_pause_ns_total{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}