apiVersion: 1

datasources:
  - name: Loki
    type: loki
    url: http://loki:3100
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - name: TraceID
          matcherRegex: '"trace_id"\s*:\s*"(.+?)"'
          url: /explore
          datasourceUid: prometheus
        - name: UserID
          matcherRegex: '"user_id"\s*:\s*"(.+?)"'
          url: /explore
