{
 "title": "OTel HTTP Metrics",
 "description": "OpenTelemetry HTTP server metrics (based on gnetId 21587).",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count,job)"
    }
   },
   {
    "name": "server_address",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count{job=~\"$job\"},server_address)"
    }
   },
   {
    "name": "http_request_method",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count{job=~\"$job\",server_address=~\"$server_address\"},http_request_method)"
    }
   },
   {
    "name": "rateinterval",
    "query": "1m,2m,3m,5m,10m,30m,1h,6h,12h,1d"
   },
   { "name": "predictive_interval", "query": "1h,2h,6h,12h,1d,2d,3d,1w" },
   { "name": "predictive_offset", "query": "1h,2h,6h,12h,1d,2d,3d,1w" }
  ]
 },
 "panels": [
  { "title": "RED Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Performance metrics overview per method during selected time range",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(http_request_method)(rate(http_server_request_duration_seconds_count{job=~\"$job\",server_address=~\"$server_address\",http_request_method=~\"$http_request_method\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (http_request_method) (increase(http_server_request_duration_seconds_sum{job=~\"$job\",server_address=~\"$server_address\",http_request_method=~\"$http_request_method\"}[$__range])) / sum by(http_request_method)(increase(http_server_request_duration_seconds_count{job=~\"$job\",server_address=~\"$server_address\",http_request_method=~\"$http_request_method\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(.95,sum(rate(http_server_request_duration_seconds_bucket{job=~\"$job\",server_address=~\"$server_address\",http_request_method=~\"$http_request_method\"}[$__range])) by(http_request_method,le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(http_request_method)(increase(http_server_request_duration_seconds_count{job=~\"$job\",server_address=~\"$server_address\",http_request_method=~\"$http_request_method\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(http_request_method) (http_server_request_duration_seconds_count{job=~\"$job\",server_address=~\"$server_address\",http_request_method=~\"$http_request_method\",http_response_status_code=~\"2..\"}) / sum by(http_request_method) (http_server_request_duration_seconds_count{job=~\"$job\",server_address=~\"$server_address\",http_request_method=~\"$http_request_method\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TPS per method over last $rateinterval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(http_request_method)(rate(http_server_request_duration_seconds_count{job=~\"$job\",server_address=~\"$server_address\",http_request_method=~\"$http_request_method\"}[$rateinterval]))",
     "legendFormat": "{{http_request_method}}"
    }
   ]
  },
  {
   "title": "P95 per method over $rateinterval interval",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.95,sum(rate(http_server_request_duration_seconds_bucket{job=~\"$job\",server_address=~\"$server_address\",http_request_method=~\"$http_request_method\"}[$rateinterval])) by(http_request_method, le))",
     "legendFormat": "{{http_request_method}}"
    }
   ]
  },
  {
   "title": "P95 over selected time range",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(.95,sum(rate(http_server_request_duration_seconds_bucket{job=~\"$job\",server_address=~\"$server_address\",http_request_method=~\"$http_request_method\"}[$__range])) by(http_request_method,le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response time distribution in seconds over selected time range",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (increase(http_server_request_duration_seconds_bucket{job=~\"$job\",server_address=~\"$server_address\",http_request_method=~\"$http_request_method\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}