FROM grafana/grafana-oss:12.3.3

# Copy provisioning configurations
COPY apps/grafana/provisioning/datasources /etc/grafana/provisioning/datasources
COPY apps/grafana/provisioning/dashboards /etc/grafana/provisioning/dashboards

EXPOSE 3000

CMD [""]
