{
 "title": "Auth Server Metrics (GRPC)",
 "description": "gRPC-go service monitoring",
 "tags": [
  "gRPC",
  "go",
  "server"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(go_memstats_alloc_bytes,job)"
    }
   },
   { "name": "interval", "query": "1m,5m,10m,15m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Success",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - ((sum(rate(rpc_server_call_duration_seconds_count{job=\"$job\",rpc_response_status_code=\"Internal\",rpc_system_name=\"grpc\"}[$interval])) + \nsum(rate(rpc_server_call_duration_seconds_count{job=\"$job\",rpc_response_status_code=\"Unknown\",rpc_system_name=\"grpc\"}[$interval])) +\nsum(rate(rpc_server_call_duration_seconds_count{job=\"$job\",rpc_response_status_code=\"Unavailable\",rpc_system_name=\"grpc\"}[$interval])) + \nsum(rate(rpc_server_call_duration_seconds_count{job=\"$job\",rpc_response_status_code=\"Unimplemented\",rpc_system_name=\"grpc\"}[$interval]))\n) / sum(rate(rpc_server_call_duration_seconds_count{job=\"$job\",rpc_system_name=\"grpc\"}[$interval])))"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(rpc_server_call_duration_seconds_count{job=\"$job\",rpc_system_name=\"grpc\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \n  sum(rate(rpc_server_call_duration_seconds_bucket{job=\"$job\",rpc_system_name=\"grpc\"}[$interval])) by (le)\n)",
     "legendFormat": "95%"
    }
   ]
  },
  { "title": "Go Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(go_goroutines{job=\"$job\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(go_gc_duration_seconds{job=\"$job\"}) by (quantile)",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(go_memstats_alloc_bytes{job=\"$job\"})",
     "legendFormat": "bytes allocated"
    },
    {
     "expr": "avg(rate(go_memstats_alloc_bytes_total{job=\"$job\"}[$interval]))",
     "legendFormat": "alloc rate"
    },
    {
     "expr": "avg(go_memstats_stack_inuse_bytes{job=\"$job\"})",
     "legendFormat": "stack inuse"
    },
    {
     "expr": "avg(go_memstats_heap_inuse_bytes{job=\"$job\"})",
     "legendFormat": "heap inuse"
    }
   ]
  },
  {
   "title": "DB connection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(go_sql_stats_connections_in_use{job=\"$job\"})",
     "legendFormat": "inuse conn"
    },
    {
     "expr": "avg(go_sql_stats_connections_idle{job=\"$job\"})",
     "legendFormat": "idle conn"
    },
    {
     "expr": "avg(go_sql_stats_connections_open{job=\"$job\"})",
     "legendFormat": "open conn"
    },
    {
     "expr": "avg(rate(go_sql_stats_connections_waited_for{job=\"$job\"}[$interval]))",
     "legendFormat": "wait conn"
    },
    {
     "expr": "avg(rate(go_sql_stats_connections_blocked_seconds{job=\"$job\"}[$interval]))",
     "legendFormat": "wait time"
    }
   ]
  },
  { "title": "gRPC Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(rpc_server_call_duration_seconds_count{job=\"$job\",rpc_response_status_code=\"OK\",rpc_system_name=\"grpc\"}[$interval]))\n/ sum(rate(rpc_server_call_duration_seconds_count{job=\"$job\",rpc_system_name=\"grpc\"}[$interval]))",
     "legendFormat": "OK"
    },
    {
     "expr": "(sum(rate(rpc_server_call_duration_seconds_count{job=\"$job\",rpc_response_status_code=\"InvalidArgument\",rpc_system_name=\"grpc\"}[$interval])) +\nsum(rate(rpc_server_call_duration_seconds_count{job=\"$job\",rpc_response_status_code=\"NotFound\",rpc_system_name=\"grpc\"}[$interval])) + \nsum(rate(rpc_server_call_duration_seconds_count{job=\"$job\",rpc_response_status_code=\"AlreadyExists\",rpc_system_name=\"grpc\"}[$interval])) + \nsum(rate(rpc_server_call_duration_seconds_count{job=\"$job\",rpc_response_status_code=\"Unauthenticated\",rpc_system_name=\"grpc\"}[$interval])) +\nsum(rate(rpc_server_call_duration_seconds_count{job=\"$job\",rpc_response_status_code=\"PermissionDenied\",rpc_system_name=\"grpc\"}[$interval])) + \nsum(rate(rpc_server_call_duration_seconds_count{job=\"$job\",rpc_response_status_code=\"FailedPrecondition\",rpc_system_name=\"grpc\"}[$interval]))\n)/ sum(rate(rpc_server_call_duration_seconds_count{job=\"$job\",rpc_system_name=\"grpc\"}[$interval]))",
     "legendFormat": "ClientError"
    },
    {
     "expr": "(sum(rate(rpc_server_call_duration_seconds_count{job=\"$job\",rpc_response_status_code=\"Internal\",rpc_system_name=\"grpc\"}[$interval])) +\nsum(rate(rpc_server_call_duration_seconds_count{job=\"$job\",rpc_response_status_code=\"Unknown\",rpc_system_name=\"grpc\"}[$interval])) + \nsum(rate(rpc_server_call_duration_seconds_count{job=\"$job\",rpc_response_status_code=\"Unavailable\",rpc_system_name=\"grpc\"}[$interval])) +\nsum(rate(rpc_server_call_duration_seconds_count{job=\"$job\",rpc_response_status_code=\"Unimplemented\",rpc_system_name=\"grpc\"}[$interval]))\n)/ sum(rate(rpc_server_call_duration_seconds_count{job=\"$job\",rpc_system_name=\"grpc\"}[$interval]))",
     "legendFormat": "ServerError"
    }
   ]
  },
  {
   "title": "Status distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(rpc_server_call_duration_seconds_count{job=\"$job\",rpc_system_name=\"grpc\"}[$interval])) by (rpc_response_status_code)\n/ ignoring(rpc_response_status_code) group_left sum(rate(rpc_server_call_duration_seconds_count{job=\"$job\",rpc_system_name=\"grpc\"}[$interval]))",
     "legendFormat": "{{rpc_response_status_code}}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(rpc_server_call_duration_seconds_count{job=\"$job\",rpc_system_name=\"grpc\"}[$interval])) by (rpc_method)",
     "legendFormat": "{{rpc_method}}"
    }
   ]
  },
  {
   "title": "Request distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(rpc_server_call_duration_seconds_count{job=\"$job\",rpc_system_name=\"grpc\"}[$interval])) by (rpc_method) \n/ ignoring(rpc_method) group_left sum(rate(rpc_server_call_duration_seconds_count{job=\"$job\",rpc_system_name=\"grpc\"}[$interval]))",
     "legendFormat": "{{rpc_method}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \n  sum(rate(rpc_server_call_duration_seconds_bucket{job=\"$job\",rpc_system_name=\"grpc\"}[$interval])) by (rpc_method,le)\n)",
     "legendFormat": "{{rpc_method}}"
    }
   ]
  },
  {
   "title": "Latency distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  sum(rate(rpc_server_call_duration_seconds_bucket{job=\"$job\",rpc_system_name=\"grpc\"}[$interval])) by (le)\n)",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.95, \n  sum(rate(rpc_server_call_duration_seconds_bucket{job=\"$job\",rpc_system_name=\"grpc\"}[$interval])) by (le)\n)",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.90, \n  sum(rate(rpc_server_call_duration_seconds_bucket{job=\"$job\",rpc_system_name=\"grpc\"}[$interval])) by (le)\n)",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.75, \n  sum(rate(rpc_server_call_duration_seconds_bucket{job=\"$job\",rpc_system_name=\"grpc\"}[$interval])) by (le)\n)",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.50, \n  sum(rate(rpc_server_call_duration_seconds_bucket{job=\"$job\",rpc_system_name=\"grpc\"}[$interval])) by (le)\n)",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.25, \n  sum(rate(rpc_server_call_duration_seconds_bucket{job=\"$job\",rpc_system_name=\"grpc\"}[$interval])) by (le)\n)",
     "legendFormat": "25%"
    },
    {
     "expr": "histogram_quantile(0.10, \n  sum(rate(rpc_server_call_duration_seconds_bucket{job=\"$job\",rpc_system_name=\"grpc\"}[$interval])) by (le)\n)",
     "legendFormat": "10%"
    }
   ]
  },
  {
   "title": "RPC stream ops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(rpc_server_response_size_bytes_count{job=\"$job\",rpc_system_name=\"grpc\"}[$interval]))",
     "legendFormat": "sent"
    },
    {
     "expr": "sum(rate(rpc_server_request_size_bytes_count{job=\"$job\",rpc_system_name=\"grpc\"}[$interval]))",
     "legendFormat": "received"
    }
   ]
  },
  {
   "title": "RPC type distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(rpc_server_call_duration_seconds_count{job=\"$job\",rpc_system_name=\"grpc\"}[$interval])) by (rpc_method)\n/ ignoring(rpc_method) group_left sum(rate(rpc_server_call_duration_seconds_count{job=\"$job\",rpc_system_name=\"grpc\"}[$interval]))",
     "legendFormat": "{{rpc_method}}"
    }
   ]
  }
 ]
}